### ISSUE TITLE
nkn-mining Node Ubuntu 18.04. not starting

### ISSUE THREAD

**Issue by wichtigwicht** [nknorg/nkn-mining#1] opened 2018-09-26 17:51 UTC
Hey there,

running a Ubuntu 18.04. VPS, the Application does not start via double klicking nknmining, nor starting it via Terminal.

Looking forward to giving more feedback!

**Comment by AKACoder** [comment] 2018-09-28 09:30
fixed in release v0.0.2.

**Closed by AKACoder** 2018-09-28 09:30 UTC

**Comment by AKACoder** [comment] 2018-09-28 09:32
> Hey there,
> 
> running a Ubuntu 18.04. VPS, the Application does not start via double klicking nknmining, nor starting it via Terminal.
> 
> Looking forward to giving more feedback!

this issue was caused by systemd process manager, and was fixed in release v0.0.2.

**Comment by AKACoder** [comment] 2018-09-28 09:33
@wichtigwicht this issue was caused by systemd process manager, and was fixed in release v0.0.2.
